-- 02_tables.sql
-- Fact-first data model. Raw comparisons are the only recorded outcome data;
-- every aggregate is derived in 04_views.sql. Aggregates are cheap to
-- recompute and impossible to un-corrupt if they drift from the facts.
-- Safely re-runnable.

USE DATABASE ROUNDNESS_LAB;
USE SCHEMA APP;

-- One row per session. No personal data is collected: respondent_id is a
-- random UUID minted client-side at session start.
CREATE TABLE IF NOT EXISTS RESPONDENTS (
    RESPONDENT_ID       VARCHAR(36)   NOT NULL PRIMARY KEY,
    SESSION_STARTED_AT  TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    APP_SOURCE          VARCHAR(32)   NOT NULL,  -- COMMUNITY_CLOUD | SIS
    -- Present now so the future priming experiment needs no migration.
    EXPERIMENT_VARIANT  VARCHAR(32)   NOT NULL DEFAULT 'CONTROL'
)
COMMENT = 'One row per survey session.';

-- Written immediately on intro submit, so a respondent who bails partway
-- through the comparisons still contributes usable data.
CREATE TABLE IF NOT EXISTS INTRO_RESPONSES (
    RESPONDENT_ID        VARCHAR(36)   NOT NULL,
    RANDOM_NUMBER        NUMBER(3,0),  -- "pick a random number 1-100"
    UNIQUE_GUESS_NUMBER  NUMBER(3,0),  -- "the number fewest others will pick"
    SUBMITTED_AT         TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Pre-session random-number questions, one row per respondent.';

-- The fact table. Display order (LEFT/RIGHT) is stored separately from the
-- outcome (WINNER/LOSER) so left-side position bias is measurable; it is a
-- real threat to this kind of instrument. POSITION_IN_PAGE catches fatigue.
CREATE TABLE IF NOT EXISTS COMPARISONS (
    COMPARISON_ID     VARCHAR(36)   NOT NULL PRIMARY KEY,
    RESPONDENT_ID     VARCHAR(36)   NOT NULL,
    LEFT_NUMBER       NUMBER(3,0)   NOT NULL,
    RIGHT_NUMBER      NUMBER(3,0)   NOT NULL,
    WINNER_NUMBER     NUMBER(3,0)   NOT NULL,
    LOSER_NUMBER      NUMBER(3,0)   NOT NULL,
    PAGE_NUMBER       NUMBER(5,0)   NOT NULL,
    POSITION_IN_PAGE  NUMBER(3,0)   NOT NULL,
    RESPONSE_MS       NUMBER(10,0),  -- null where not captured
    SUBMITTED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'One row per pairwise comparison. The only outcome fact table.';

CREATE TABLE IF NOT EXISTS SURVEY_RESPONSES (
    RESPONDENT_ID         VARCHAR(36)   NOT NULL,
    ROUNDNESS_DEFINITION  VARCHAR(2000),
    INTUITION_FACTORS     VARCHAR(2000),
    LEAST_ROUND_NUMBER    NUMBER(3,0),
    POST_RANDOM_NUMBER    NUMBER(3,0),  -- compare against INTRO_RESPONSES
    SUBMITTED_AT          TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Post-session free text and closing questions.';

-- Populated out-of-band by 06_ai_classify_survey.sql. The public app never
-- calls Cortex: no added latency, no Cortex grants on the service role, and no
-- breakage where AI_CLASSIFY is unavailable.
CREATE TABLE IF NOT EXISTS SURVEY_CLASSIFICATIONS (
    RESPONDENT_ID   VARCHAR(36)   NOT NULL,
    CLASSIFICATION  VARCHAR(64),
    CLASSIFIED_AT   TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'AI_CLASSIFY output over SURVEY_RESPONSES free text.';

-- Reference data: 1-100 with one precomputed feature per hypothesis. This is
-- what turns the survey from a leaderboard into an experiment. Seeded by
-- 03_seed_numbers.sql, which is generated by scripts/generate_number_features.py.
CREATE TABLE IF NOT EXISTS NUMBERS (
    NUMBER_VALUE       NUMBER(3,0)  NOT NULL PRIMARY KEY,

    -- Hypothesis 1: additive units (currency)
    MIN_COIN_COUNT     NUMBER(3,0)  NOT NULL,

    -- Hypothesis 2: geometric / factors
    DIVISOR_COUNT      NUMBER(3,0)  NOT NULL,
    IS_PRIME           BOOLEAN      NOT NULL,
    IS_PERFECT_SQUARE  BOOLEAN      NOT NULL,
    ASPECT_RATIO       FLOAT        NOT NULL,  -- most-square factor pair, 1.0 = square

    -- Hypothesis 3: roundness gravity
    DIST_TO_MULT_10    NUMBER(3,0)  NOT NULL,
    DIST_TO_MULT_25    NUMBER(3,0)  NOT NULL,
    DIST_TO_MULT_50    NUMBER(3,0)  NOT NULL,
    GRAVITY_SCORE      FLOAT        NOT NULL,

    -- Hypothesis 4: Roman numerals
    ROMAN_NUMERAL      VARCHAR(16)  NOT NULL,
    ROMAN_LENGTH       NUMBER(3,0)  NOT NULL,

    -- Baseline controls
    TRAILING_ZEROS     NUMBER(2,0)  NOT NULL,
    IS_MULT_5          BOOLEAN      NOT NULL
)
COMMENT = 'Numbers 1-100 with one precomputed feature per hypothesis.';
